### ISSUE TITLE
`ck.timezone()` without `travel()` or `freeze()` has incorrect `getTimezoneOffset`

### ISSUE THREAD

**Issue by meowtec** [paed01/chronokinesis#3]
```
import * as ck from 'chronokinesis';

ck.timezone('America/Chicago');

new Date().toLocalString(); // Chicago time

new Date().getTimezoneOffset(); // My local timezone

```

To make `getTimezoneOffset` mocked, I have to call `travel()`, like this:

```
ck.timezone('America/Chicago').travel();
```

It is strange, I think when we call `timezone()`, `travel()` should be always called by default.

**Comment by paed01** [comment]
You are absolutely correct, thank you. I fixed this in v6. Give it a try.
